# name of workflow servers as a label 
name: run main.py

# on property which tells when to run 
on:
  # it is scheduled on monday
  schedule:  
    - cron: '0 0 1 * *' # a cron job to run at midnight on the first day of every month

# actual action/code running on cloud for automation tasks
jobs:
  # job is build on
  build:
    # which runs on 
    runs-on: ubuntu-latest

    # performs the following steps
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # gets the repo code 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # setups the working environment by installing tools 
          
      - name: install python packages # installs dependencies 
        run: |
          python -m pip install --upgrade pip   
          
      - name: execute py script # run main.py
        run: python main.py
          
      - name: commit files
        run : |
          git config --global user.name 'HarromPS'
          git config --global user.email 'HarromPS@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push
      
      
      - name: Check git status
        run: git status

      # - name: GitHub Push
      #   uses: ad-m/github-push-action@v0.8.0    
      #   with:
      #     github_token: ${{ secrets.TOKEN }}
      #     branch: main 