# name of workflow servers as a label 
name: run main.py

# on property which tells when to run 
on:
  # it is scheduled on monday
  schedule:  
    - cron: '*/1 * * * *' # At every minute

# actual action/code running on cloud for automation tasks
jobs:
  # job is build on
  build:
    # which runs on 
    runs-on: ubuntu-latest

    # performs the following steps
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # gets the repo code 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # setups the working environment by installing tools 
          
      - name: install python packages # installs dependencies 
        run: |
          python -m pip install --upgrade pip   
          
      - name: execute py script # run main.py
        env:
          # SOME_SECRET: ${{ secrets.SOME_SECRET }}   # configure environment variables
        run: python main.py

      - name: List files
        run: ls -R

          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
      
      
      - name: Check git status
        run: git status


      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main 